version: '2.1'
services:
  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8500 || exit 1"]
      interval: 5s
      retries: 10
    ports:
      - 8500:8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
      - 127.0.0.1

  nginx-lb:
    build: nginx/
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - 8000:8000
    expose:
      - 8000
    command: >
        /bin/containerpilot
        -config file:///etc/containerpilot/containerpilot.json
        nginx -g "daemon off;"
    

  docker-na-pratica:
    build: docker-na-pratica/
    environment:
      - BANCO_HOST
      - BANCO_PORTA
      - BANCO_DATABASE
      - BANCO_USUARIO
      - BANCO_SENHA

    

